"""new_name_cart

Revision ID: 5cc608e3838b
Revises: 3cfe5ed4f9ab
Create Date: 2024-06-25 17:53:30.679378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc608e3838b'
down_revision = '3cfe5ed4f9ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sctructures')
    op.drop_table('purchases')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchases',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('purchases_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], name='purchases_id_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='purchases_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('sctructures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_purchase', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_book', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_book'], ['books.id'], name='sctructures_id_book_fkey'),
    sa.ForeignKeyConstraint(['id_purchase'], ['purchases.id'], name='sctructures_id_purchase_fkey'),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], name='sctructures_id_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='sctructures_pkey')
    )
    # ### end Alembic commands ###
