"""Added new_column to books table

Revision ID: bbda0c98e598
Revises: 
Create Date: 2024-06-20 18:13:10.163096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbda0c98e598'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_genre', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'genres', ['id_genre'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_genre')

    # ### end Alembic commands ###
